### ISSUE TITLE
Add CI build and NuGet publishing

### ISSUE THREAD

**Issue by madskristensen** [VsixCommunity/Community.VisualStudio.VSCT#3]
@CZEMacLeod should I add the same AppVeyor CI story with automatic NuGet publishing that we use for the toolkit? We can always change both of them later to GitHub Actions if we find that needed.

**Comment by CZEMacLeod** [comment]
@madskristensen I'm good with that.

**Comment by madskristensen** [comment]
I'm realizing you already published the nuget package using your own NuGet account, so I can't setup automatic publishing unless you add me as owner as well. You don't have to, but if you want to, [here's how](https://github.com/NuGet/docs.microsoft.com-nuget/blob/main/docs/nuget-org/Publish-a-package.md#managing-package-owners-on-nugetorg) and my username is **madskristensen**.

**Comment by CZEMacLeod** [comment]
@madskristensen I knew you would need it so I already added you as an owner last week sometime. It shows you are a pending owner in nuget.org

**Comment by madskristensen** [comment]
I totally missed that. Thank you!
