### ISSUE TITLE
Redundant "Group" suffix?

### ISSUE THREAD

**Issue by quomaz** [VsixCommunity/Community.VisualStudio.VSCT#5]
As the comment in the `VSGlobals.vsct` file says...:
```
  In this file, you can tell menus and groups apart by the number of dots (.) in the name. 
  Each IDSymbol[name] follows the pattern "<Menu>.<Group>.<Menu>.<Group>.<Menu>... etc."
```
So if "Groups" are exactly placed on the odd places of the pattern (counting from 0 of course 😄) then why write `Edit.GoToGroup.GoTo.EditorGroup` if we can write `Edit.GoTo.GoTo.Editor`? By the pattern, the second `GoTo` is a _group_, and the third `GoTo` is a _menu_, so there is no room for confusion. Of course, if someone does not know the pattern, then the confusion may arise, but even then it's not really fatal, but the length of the name is shorter!

If you think adding "Group" suffix is more elegant, in spirit of different things should have different names, or some other reason, then of course I understand that.

By the way, thank you for your amazing support here at VsixCommunity!

**Comment by CZEMacLeod** [comment]
I think this was discussed in one of the live streams.
Pretty sure it was decided that having the Group suffix meant you didn't have to know the secret sauce of the alternating pattern, and that you didn't think that there was duplicate text 'by accident'.
